services:
  jupyter:
    build: .
    container_name: getting-to-philosophy
    restart: unless-stopped
    user: "1000:100"
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/notebooks
      - ./multistream:/home/jovyan/multistream
      - ./output:/home/jovyan/output

      - ./jupyter-config:/home/jovyan/.jupyter
      - ./jupyter-data:/home/jovyan/.local/share/jupyter
